---
swagger: "2.0"
info:
  description: "Web-Shiori API document"
  version: "1.0.0"
  title: "Web-Shiori API"
  contact:
    email: "shiori.web.forsafari@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "web-shiori-api-document.herokuapp.com"
tags:
- name: "auth"
  description: "認証関連API"
- name: "content"
  description: "コンテンツ関連API"
- name: "folder"
  description: "フォルダ関連API"
schemes:
- "https"
paths:
  /v1/auth:
    post:
      tags:
      - "auth"
      summary: "会員登録用API"
      description: "会員登録します。\n email, password, password_confirmationをリクエストで受け取り、ユ\
        ーザと認証用のトークンを生成します。"
      operationId: "v1AuthPOST"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Request Body"
        required: true
        schema:
          $ref: "#/definitions/AuthRequest"
      responses:
        "200":
          description: "A successful response."
          schema:
            $ref: "#/definitions/AuthResponse"
      x-swagger-router-controller: "Auth"
definitions:
  AuthRequest:
    type: "object"
    properties:
      email:
        type: "string"
        description: "メールアドレス"
      password:
        type: "string"
        description: "パスワード"
      password_confirmation:
        type: "string"
        description: "パスワード(確認用)"
    example:
      password: "password"
      password_confirmation: "password_confirmation"
      email: "email"
  AuthResponse:
    type: "object"
    properties:
      status:
        type: "string"
        example: "success"
        description: "status"
    example:
      status: "success"
